"""Exchange-agnostic core models for trading research workflows."""

from __future__ import annotations

from dataclasses import dataclass, field
from decimal import Decimal
from enum import StrEnum
from typing import Literal

ZERO = Decimal("0")
ONE = Decimal("1")
TWO = Decimal("2")


class ExecutionMode(StrEnum):
    """Supported non-production execution modes.

    `LIVE_DISABLED` is intentionally a disabled state, not an enabled live mode.
    """

    BACKTEST = "backtest"
    PAPER = "paper"
    DEMO = "demo"
    LIVE_DISABLED = "live_disabled"


@dataclass(frozen=True, slots=True)
class OrderBookLevel:
    """A price/quantity level in a normalized orderbook."""

    price: Decimal
    quantity: Decimal

    def __post_init__(self) -> None:
        _require_decimal(self.price, field_name="price")
        _require_decimal(self.quantity, field_name="quantity")
        _validate_probability_price(self.price, field_name="price")
        _validate_positive(self.quantity, field_name="quantity")


@dataclass(frozen=True, slots=True)
class NormalizedOrderBook:
    """Canonical bid/ask representation for one instrument."""

    instrument_id: str
    bids: tuple[OrderBookLevel, ...] = field(default_factory=tuple)
    asks: tuple[OrderBookLevel, ...] = field(default_factory=tuple)
    source: str = "unknown"

    def __post_init__(self) -> None:
        bids = tuple(sorted(self.bids, key=lambda level: level.price, reverse=True))
        asks = tuple(sorted(self.asks, key=lambda level: level.price))
        object.__setattr__(self, "bids", bids)
        object.__setattr__(self, "asks", asks)

        if not self.instrument_id:
            msg = "instrument_id is required"
            raise ValueError(msg)
        if self.best_bid is not None and self.best_ask is not None and self.is_locked_or_crossed:
            msg = "normalized orderbook is locked or crossed"
            raise ValueError(msg)

    @property
    def best_bid(self) -> OrderBookLevel | None:
        return self.bids[0] if self.bids else None

    @property
    def best_ask(self) -> OrderBookLevel | None:
        return self.asks[0] if self.asks else None

    @property
    def best_bid_price(self) -> Decimal | None:
        return self.best_bid.price if self.best_bid else None

    @property
    def best_ask_price(self) -> Decimal | None:
        return self.best_ask.price if self.best_ask else None

    @property
    def spread(self) -> Decimal | None:
        if self.best_bid is None or self.best_ask is None:
            return None
        return self.best_ask.price - self.best_bid.price

    @property
    def mid(self) -> Decimal | None:
        if self.best_bid is None or self.best_ask is None:
            return None
        return (self.best_bid.price + self.best_ask.price) / TWO

    @property
    def bid_depth(self) -> Decimal:
        return sum((level.quantity for level in self.bids), ZERO)

    @property
    def ask_depth(self) -> Decimal:
        return sum((level.quantity for level in self.asks), ZERO)

    @property
    def is_locked_or_crossed(self) -> bool:
        if self.best_bid is None or self.best_ask is None:
            return False
        return self.best_bid.price >= self.best_ask.price


@dataclass(frozen=True, slots=True)
class Instrument:
    """Exchange-agnostic instrument metadata."""

    instrument_id: str
    display_name: str
    market_type: str = "binary_prediction"
    settlement_currency: str = "USD"

    def __post_init__(self) -> None:
        if not self.instrument_id:
            msg = "instrument_id is required"
            raise ValueError(msg)
        if not self.display_name:
            msg = "display_name is required"
            raise ValueError(msg)


@dataclass(frozen=True, slots=True)
class Quote:
    """A two-sided quote generated by a research strategy."""

    instrument_id: str
    bid_price: Decimal
    ask_price: Decimal
    bid_quantity: Decimal
    ask_quantity: Decimal

    def __post_init__(self) -> None:
        _require_decimal(self.bid_price, field_name="bid_price")
        _require_decimal(self.ask_price, field_name="ask_price")
        _require_decimal(self.bid_quantity, field_name="bid_quantity")
        _require_decimal(self.ask_quantity, field_name="ask_quantity")
        _validate_probability_price(self.bid_price, field_name="bid_price")
        _validate_probability_price(self.ask_price, field_name="ask_price")
        _validate_non_negative(self.bid_quantity, field_name="bid_quantity")
        _validate_non_negative(self.ask_quantity, field_name="ask_quantity")

        if self.bid_price >= self.ask_price:
            msg = "quote bid_price must be less than ask_price"
            raise ValueError(msg)


@dataclass(frozen=True, slots=True)
class OrderIntent:
    """A desired order action before risk approval and execution."""

    instrument_id: str
    side: Literal["buy", "sell"]
    price: Decimal
    quantity: Decimal
    execution_mode: ExecutionMode
    reason: str = ""

    def __post_init__(self) -> None:
        _require_decimal(self.price, field_name="price")
        _require_decimal(self.quantity, field_name="quantity")
        _validate_probability_price(self.price, field_name="price")
        _validate_positive(self.quantity, field_name="quantity")
        if self.side not in {"buy", "sell"}:
            msg = "side must be 'buy' or 'sell'"
            raise ValueError(msg)
        if self.execution_mode is ExecutionMode.LIVE_DISABLED:
            msg = "LIVE_DISABLED is not an executable order mode"
            raise ValueError(msg)


@dataclass(frozen=True, slots=True)
class Position:
    """Position and realized accounting state for one instrument."""

    instrument_id: str
    quantity: Decimal
    average_price: Decimal
    realized_pnl: Decimal = ZERO
    fees_paid: Decimal = ZERO

    def __post_init__(self) -> None:
        _require_decimal(self.quantity, field_name="quantity")
        _require_decimal(self.average_price, field_name="average_price")
        _require_decimal(self.realized_pnl, field_name="realized_pnl")
        _require_decimal(self.fees_paid, field_name="fees_paid")
        _validate_probability_price(self.average_price, field_name="average_price")
        _validate_non_negative(self.fees_paid, field_name="fees_paid")


@dataclass(frozen=True, slots=True)
class RiskLimits:
    """Risk limits that future execution paths must evaluate before action."""

    max_position_abs: Decimal
    max_order_quantity: Decimal
    max_notional: Decimal
    max_daily_loss: Decimal

    def __post_init__(self) -> None:
        _require_decimal(self.max_position_abs, field_name="max_position_abs")
        _require_decimal(self.max_order_quantity, field_name="max_order_quantity")
        _require_decimal(self.max_notional, field_name="max_notional")
        _require_decimal(self.max_daily_loss, field_name="max_daily_loss")
        _validate_non_negative(self.max_position_abs, field_name="max_position_abs")
        _validate_non_negative(self.max_order_quantity, field_name="max_order_quantity")
        _validate_non_negative(self.max_notional, field_name="max_notional")
        _validate_non_negative(self.max_daily_loss, field_name="max_daily_loss")


@dataclass(frozen=True, slots=True)
class RiskDecision:
    """Auditable pre-execution risk decision."""

    approved: bool
    reason: str
    limit_name: str | None = None

    def __post_init__(self) -> None:
        if not self.reason:
            msg = "risk decisions require a reason"
            raise ValueError(msg)


def _require_decimal(value: Decimal, *, field_name: str) -> None:
    if not isinstance(value, Decimal):
        msg = f"{field_name} must be a Decimal"
        raise TypeError(msg)


def _validate_probability_price(value: Decimal, *, field_name: str) -> None:
    if value < ZERO or value > ONE:
        msg = f"{field_name} must be between 0 and 1"
        raise ValueError(msg)


def _validate_positive(value: Decimal, *, field_name: str) -> None:
    if value <= ZERO:
        msg = f"{field_name} must be positive"
        raise ValueError(msg)


def _validate_non_negative(value: Decimal, *, field_name: str) -> None:
    if value < ZERO:
        msg = f"{field_name} must be non-negative"
        raise ValueError(msg)
